name: Deploy Extensions

on:
  push:
    branches: [main]
    paths:
      - "extensions/**/package.json"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build all extensions
        run: |
          for pkg_dir in extensions/*; do
            if [ -f "$pkg_dir/package.json" ]; then
              echo "Building $pkg_dir..."
              npm run --workspace $pkg_dir build || true
            fi
          done

      - name: Copy builds to root
        run: |
          for pkg_dir in extensions/*; do
            if [ -f "$pkg_dir/package.json" ]; then
              DIR_NAME=$(basename $pkg_dir)
              rm -rf $DIR_NAME
              mkdir -p $DIR_NAME
              if [ -d "$pkg_dir/dist" ]; then
                cp -r $pkg_dir/dist/* $DIR_NAME/
              fi
            fi
          done

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update extensions" || echo "No changes to commit"
          git push origin gh-pages
