name: Live Italy - Deploy EPG Guide

on:
  schedule:
    - cron: "0 2 * * *" # Runs at 2:00 AM UTC every day
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate EPG Guide
        run: npm run --workspace extensions/live-italy make-guide

      - name: Clone gh-pages branch
        run: |
          git clone --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages

      - name: Copy EPG guide to gh-pages
        run: |
          rm -rf gh-pages/data/live-italy
          mkdir -p gh-pages/data/live-italy
          cp ./extensions/live-italy/assets/data/epg-guide.json gh-pages/data/live-italy/
          cp ./extensions/live-italy/public/index.html gh-pages/data/live-italy/

      - name: Commit & push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Live Italy EPG Guide" || echo "No changes to commit"
          git push origin gh-pages
